### PR TITLE
Make TLS and Authorization Configuration Fields Optional

### LINKED ISSUE #565: TLSNotary server wont start without `private-key-pem-path` defined even when its unused
I just set up a TLSNotary server here: https://tlsnotary.zervice.io/ and [wrote a guide for others](https://docs.monadical.com/s/UrN0j1lpu) in the process, but I encountered a minor issue in the process that I think is a bug.

TLSNotary fails to start when any of `private-key-pem-path`, `certificate-pem-path`, or `whitelist-csv-path` are missing from `config.yaml`, even when the `tls` and `authorization` sections are disabled with `enabled: false`.

According to the (excellent) docs, those files should not be needed when those features are disabled:
image

---

### Error Output

```bash
tlsnotary-1  | Location:
tlsnotary-1  |     /usr/src/tlsn/notary/server/src/util.rs:7:21)
tlsnotary-1  | Error: Unexpected(tls: missing field `private-key-pem-path` at line 20 column 3
tlsnotary-1  | Location:
tlsnotary-1  |     /usr/src/tlsn/notary/server/src/util.rs:7:21)
tlsnotary-1  | Error: Unexpected(authorization: missing field `whitelist-csv-path` at line 30 column 3
```

---

### Steps to reproduce

Full steps to reproduce here: https://docs.monadical.com/s/UrN0j1lpu

`docker-compose.yml`:
```yaml
services:
    tlsnotary:
        # https://github.com/tlsnotary/tlsn/pkgs/container/tlsn%2Fnotary-server
        image: ghcr.io/tlsnotary/tlsn/notary-server:latest
        volumes:
          - ./tlsnotary:/root/.notary-server/config:ro
```

`./tlsnotary/config.yaml`:
```yaml
# copied from: https://github.com/tlsnotary/tlsn/blob/main/notary/server/config/config.yaml

server:
  name: "notary-server"
  host: "0.0.0.0"
  port: 80
  html-info: |
    <h1>Notary Server {version}!</h1>
    <ul>
    <li>git commit hash: <a href="https://github.com/tlsnotary/tlsn/commit/{git_commit_hash}">{git_commit_hash}</a></li>
    <li>git commit timestamp: {git_commit_timestamp}</li>
    <li>public key: <pre>{public_key}</pre></li>
    </ul>
    <a href="/healthcheck">health check</a> - <a href="/info">info</a><br/>

notarization:
  max-transcript-size: 20480

tls:
  enabled: false
  # BUG: these are unused when enabled=false, but tlsnotary will fail to start without them:
  # private-key-pem-path: "/letsencrypt/live/$DOMAIN/privkey.pem"
  # certificate-pem-path: "/letsencrypt/live/$DOMAIN/fullchain.pem"

notary-key:
  private-key-pem-path: "/root/.notary-server/config/notary.key"
  public-key-pem-path: "/root/.notary-server/config/notary.pub"

authorization:
  enabled: false
  # BUG: this must still be set even if auth is not enabled or it will fail to start:
  # whitelist-csv-path: "/root/.notary-server/config/whitelist.csv"

logging:
  level: DEBUG
```

If I create empty files in those locations and uncomment those lines in `config.yaml` then it starts without issue.

### PR DESCRIPTION
**Pull request by yorozunouchu**
This pull request fixes #565 where the TLSNotary server fails to start when specific configuration fields (`private_key_pem_path`, `certificate_pem_path`, and `whitelist_csv_path`) are missing, even when the corresponding features are disabled.

Please review and provide feedback!

### CODE REVIEW

File: notary/server/src/server.rs [hunk 1]
```diff
@@ -228,15 +228,18 @@ async fn load_notary_signing_key(config: &NotarySigningKeyProperties) -> Result<
 }
 
 /// Read a PEM-formatted file and return its buffer reader
-pub async fn read_pem_file(file_path: &str) -> Result<BufReader<StdFile>> {
+pub async fn read_pem_file(file_path: &Option<String>) -> Result<BufReader<StdFile>> {
```
Comment (yuroitaki) [inline notary/server/src/server.rs:231]: keep this "Option handling" logic outside of these specific functions; the logic can be handled outside [here](https://github.com/tlsnotary/tlsn/blob/dev/crates/notary/server/src/server.rs#L61-L65)

File: notary/server/src/server.rs [hunk 2]
```diff
@@ -228,15 +228,18 @@ async fn load_notary_signing_key(config: &NotarySigningKeyProperties) -> Result<
...
+    })?;
     let key_file = File::open(file_path).await?.into_std().await;
     Ok(BufReader::new(key_file))
 }
 
 /// Load notary tls private key and cert from static files
 async fn load_tls_key_and_cert(
-    private_key_pem_path: &str,
-    certificate_pem_path: &str,
+    private_key_pem_path: &Option<String>,
```
Comment (yuroitaki) [inline notary/server/src/server.rs:241]: same as above

File: notary/server/src/server.rs [hunk 3]
```diff
@@ -266,11 +269,15 @@ fn load_authorization_whitelist(
         debug!("Skipping authorization as it is turned off.");
         None
     } else {
+        // Check if whitelist_csv_path is Some and convert to &str
+        let whitelist_csv_path = config
+            .authorization
+            .whitelist_csv_path
+            .as_deref()
+            .ok_or_else(|| eyre!("Whitelist CSV path is not provided in the config"))?;
```
Comment (yuroitaki) [inline notary/server/src/server.rs:277]:
```suggestion
            .ok_or_else(|| eyre!("Authorization whitelist csv path is not provided in the config"))?;
```

File: notary/server/src/server.rs [hunk 4]
```diff
@@ -318,13 +325,20 @@ fn watch_and_reload_authorization_whitelist(
         )
         .map_err(|err| eyre!("Error occured when setting up watcher for hot reload: {err}"))?;
 
+        // Check if whitelist_csv_path is Some and convert to &str
+        let whitelist_csv_path = config
+            .authorization
+            .whitelist_csv_path
+            .as_deref()
+            .ok_or_else(|| eyre!("Whitelist CSV path is not provided in the config"))?;
```
Comment (yuroitaki) [inline notary/server/src/server.rs:333]:
```suggestion
            .ok_or_else(|| eyre!("Authorization whitelist CSV path is not provided in the config"))?;
```

**Review by yuroitaki — CHANGES_REQUESTED** [review]
Thanks for the PR guys! Few comments, and also
- base your PR on dev instead of main
- remember to follow the guideline [here](https://github.com/tlsnotary/tlsn/blob/dev/CONTRIBUTING.md#pull-requests)

File: crates/notary/server/src/server.rs [hunk 5]
```diff
@@ -59,22 +59,26 @@ pub async fn run_server(config: &NotaryServerProperties) -> Result<(), NotarySer
...
-            .with_safe_defaults()
-            .with_no_client_auth()
-            .with_single_cert(tls_certificates, tls_private_key)
-            .map_err(|err| eyre!("Failed to instantiate notary server tls config: {err}"))?;
-
-        // Set the http protocols we support
-        server_config.alpn_protocols = vec![b"http/1.1".to_vec()];
-        let tls_config = Arc::new(server_config);
-        Some(TlsAcceptor::from(tls_config))
+        if let (Some(private_key_path), Some(certificate_pem_path)) = (
```
Comment (yuroitaki) [inline crates/notary/server/src/server.rs:62]: if the pem paths are not set when `tls.enabled` is true, we should throw an error — like your line 297

**Review by yuroitaki — CHANGES_REQUESTED** [review]
Remember to base your PR on dev instead of main~

File: crates/notary/server/src/server.rs (hunk 5 above)
Comment (yorozunouchu) [reply crates/notary/server/src/server.rs:64]: we have updated pr to be based on the dev branch instead of the main branch and added validation to throw an error when TLS is enabled but PEM paths are not set.

Comment (yuroitaki) [reply crates/notary/server/src/server.rs:64]: @yorozunouchu i didn't see the error throwing fix yet, have you guys pushed it? right now if paths are not set it's still returning `None`, but we need it to throw error — so instead of doing `if let Some(path)...` just directly do something like `path.ok_or_else(...)?`

**Comment by yuroitaki** [comment]
@yorozunouchu the CI fails because of clippy and formatting; can you guys follow the guidelines here https://github.com/tlsnotary/tlsn/blob/dev/CONTRIBUTING.md#linting and https://github.com/tlsnotary/tlsn/blob/dev/CONTRIBUTING.md#style

**Review by yuroitaki — APPROVED** [review]
Amazing work, thanks so much again @yorozunouchu and @funkyenough !
