### PR TITLE
fix(server): use custom HTTP header for authorization: X-API-Key

### LINKED ISSUE #803: server: notary server requires HTTP "Authorization" header without specifying authentication scheme
Tweak the default server config to enable whitelisting for the `/session` route:

```diff
diff --git a/crates/notary/server/config/config.yaml b/crates/notary/server/config/config.yaml
index 476157ba..88283b06 100644
--- a/crates/notary/server/config/config.yaml
+++ b/crates/notary/server/config/config.yaml
@@ -30,7 +30,7 @@ notarization:
   timeout: 1800

 tls:
-  enabled: true
+  enabled: false
   private_key_pem_path: "./fixture/tls/notary.key"
   certificate_pem_path: "./fixture/tls/notary.crt"

@@ -42,7 +42,7 @@ logging:
   level: DEBUG

 authorization:
-  enabled: false
+  enabled: true
   whitelist_csv_path: "./fixture/auth/whitelist.csv"

 concurrency: 32
```

Now, pass one of the test tokens in [`whitelist.csv`](https://github.com/tlsnotary/tlsn/blob/main/crates/notary/server/fixture/auth/whitelist.csv) in the "Authorization" header:

* if passed *without* specifying the authentication scheme, the server accepts the request

```
$ curl -X POST -H "Authorization: test_api_key_0" "http://127.0.0.1:7047/session"
Invalid request from prover: Expected request with `Content-Type: application/json`
```

* if passed *with* authentication scheme "Bearer" for example (the scheme doesn't matter as it incorrectly becomes part of the supplied auth token), the server *incorrectly* denies the request

```
$ curl -X POST -H "Authorization: Bearer test_api_key_0" "http://127.0.0.1:7047/session"
Unauthorized request from prover: Invalid API key.
```

### PR DESCRIPTION
**Pull request by kubkon**
Fixes #803 

cc @yuroitaki

### CODE REVIEW

File: crates/notary/server/src/middleware.rs [hunk 1]
```diff
@@ -11,6 +11,8 @@ use crate::{
 /// Auth middleware to prevent DOS
 pub struct AuthorizationMiddleware;
 
+pub const X_API_KEY_HEADER: &str = "X-API-Key";
```
[the remark this answers is not in the document]
Comment (kubkon) [reply crates/notary/server/src/middleware.rs]: Addressed in 4ef9344

File: crates/notary/server/src/domain/auth.rs [hunk 2]
```diff
@@ -1,6 +1,9 @@
 use serde::{Deserialize, Serialize};
 use std::collections::HashMap;
 
+/// Custom HTTP header used for specifying whitelisted API keys
```
Comment (yuroitaki) [inline crates/notary/server/src/domain/auth.rs:4]:
```suggestion
/// Custom HTTP header used for specifying a whitelisted API key
```

File: crates/notary/server/openapi.yaml [hunk 3]
```diff
@@ -218,3 +207,8 @@ components:
       - version
       - publicKey
       - gitCommitHash
+  securitySchemes:
+    ApiKeyAuth:
+      type: apiKey
+      in: header
+      name: X-API-Key
```
Comment (yuroitaki) [inline crates/notary/server/openapi.yaml:214]:
```suggestion
      name: X-API-Key
      description: Whitelisted API key if auth module is turned on
```

**Review by yuroitaki — CHANGES_REQUESTED** [review]
nice, just two nits

**Comment by kubkon** [comment]
> nice, just two nits

Comments addressed, and I've squashed all the fixups into a single commit too.

**Review by yuroitaki — APPROVED** [review]
good work, thanks!
